### ISSUE TITLE
Display Specific User Avatar

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/avatar#2]
Will this module allow me to display a specific user's avatar?

**Comment by signalpoint** [comment]
@mkinnan If you have the fully loaded account object, yes.

```
var html = theme('avatar', account);
```

Otherwise you can fake it (i.e. in case you have Views results rows, and not fully loaded account objects):

```
var html = theme('avatar', { uid: row.uid, picture: { uri: row.picture.src } });
```

**Comment by mkinnan** [comment]
Is it possible to load image styles? I have a horrible work around at the moment.

**Comment by signalpoint** [comment]
With Views yes, because you can select the image style up in Drupal. But with a fully loaded account, probably not. The theme_avatar function would need to be expanded to watch for an incoming image_style machine name, and then use this function to build the image src: http://api.drupalgap.org/7/global.html#image_style_url

**Comment by mkinnan** [comment]
I'm trying to load user 'thumbnails' for nodes and comments. I've rewritten the way comments are displayed on nodes to make it look like Facebook comments. The issue is the varying image sizes and amount of bandwidth to load a few dozen user full size avatars scaled down via CSS.

**Comment by mkinnan** [comment]
My current hack ... i created a text field on my nodes for storing the author's avatar filename. When user creates a new node, a rule automatically populates the filename field. This approach suffers from not generating image style images and updating the filename of all the nodes when a user changes their avatar. I don't think rules can be triggered for avatar changes in the module's current state, correct?

Alternatively, it's probably pretty easy to create a services function for sending userid and image style that returns current avatar image style uri.

Thoughts?

**Comment by mkinnan** [comment]
Missed your comment earlier about using `image_style_url`. Don't you also need a function for **image_style_path** in drupalgap to get the URI to pass to `image_style_url` to get the URL to use as the **src** for then displaying the image in HTML?

https://www.drupal.org/node/2050669

**Comment by mkinnan** [comment]
What is the recommended way to get a user's full account object to pass to:

```
  var html = theme('avatar', account);
```

in order to display a specific user's avatar since it seems **user_load()** is probably not the way to go ...

**Comment by signalpoint** [comment]
@mkinnan It depends if you're showing a list of user's or just a single user. If it's a list, we'll obviously use Views, so hopefully Views can deliver the uri, e.g. `public:\\foo.jpg`, so then you can use:

```
var html = theme('avatar', { uid: row.uid, picture: { uri: row.uri } });
```

Otherwise, lately I've been completely bypassing many of the built in pages in Drupal for viewing nodes and users, and instead just building my own page:

http://docs.drupalgap.org/7/Entities/Rendering_Entities

I've come to the sad conclusion, that the built in `node/%` and `user/%` pages are only for super simple apps, but when you want more complete control, the link above is a great technique.

This latter technique is definitely for viewing one particular entity, but will have the fully loaded entity delivered to your "render" function, at which point you could then easily use a fully loaded user account object to render the avatar.

**Comment by mkinnan** [comment]
@signalpoint ... I'll have to investigate the Rendering Entities page. I am trying to load an image styled avatar of a single user. Here's what I did that appears to be a simple solution and doesn't require any additionally calls between the app and the server ... at least from what I understand.

Install Computed Field module:
https://www.drupal.org/project/computed_field

Create a field with a machine name **field_author_avatar_image**. You can name it anything you want but will require changes to the rest of the code snippets. In the Computed Code (PHP) section, paste the following snippet:

```
$entity_field[0]['value'] = "";

$userid = $entity->uid;

$account = user_load($entity->uid);

// change thumbnail to your preferred image style
$url = image_style_url('thumbnail', $account->picture->uri);

$entity_field[0]['value'] = '<img class="author-info" src="' . $url . '"  />';
```

Set permissions to _custom_ on the field. Check the box **Recalculate the field value every time.** and uncheck the box **Store value in the database**. Set the data type to varchar or text with a data length of 255.

Then on the permissions page, set **View anyone's value for field Author Avatar Image** to _anonymous user_. 

In your DrupalGap module code, get the HTML code for displaying the image as follows:

```
  var author_avatar = entity.field_author_avatar_image.und['0']['value'];
```

This should be applicable to any entity ... nodes, comments, etc.

**Comment by signalpoint** [comment]
@mkinnan Interesting, thank you for sharing a work around. Please feel free to close this issue if you're all set, thanks.

**Comment by mkinnan** [comment]
So far, the Computed Field approach works great! It even works perfectly for comments too.
